### ISSUE TITLE
[Bug] - Unable to render html in select dropdown

### ISSUE THREAD

**Issue by shakum3012** [freshworks/crayons#105]
**Component**
fw-select-option

**Describe the bug**
Unable to render html in as a drop-down choice. The html-content value is <fw-icon name="arrow-right"></fw-icon>. 
As per the documentation the choice displayed must be a right arrow. However, the choice was not displayed. Further, using the unicode value in the html to display the right arrow also didnt seem to work.

**To Reproduce**
Steps to reproduce the current behavior:
Use the below code and render:
`<fw-select name="syncType" label="Sync Setting" required placeHolder="Choose the type of sync">
               <fw-select-option  value="fd_sf" html html-content="<fw-icon name=&quot;arrow-right&quot;>"></fw-select-option>
</fw-select>`

**Expected behavior**
Html content must be displayed as the choice label.

**Comment by asifahmedfw** [comment]
@shakum3012 `<fw-icon name='arrow-right'>` works for me.
Can you send us screenshots as well, along with any errors reported on the console?

**Comment by shravan-balasubramanian** [comment]
`<fw-select
    label="Select App type"
    placeholder="Choose app type"
    value="2"
    >
        <fw-select-option value="1" html option-text="LLL">
              <div style="color: red; padding: 10px;">Lannister </div class="cls">
              <div style="color: green; padding: 5px;">Lannisters are gods</div>
        </fw-select-option>
        <fw-select-option value="2">
          Shenigans
        </fw-select-option>
</fw-select>`

Hey @shakum3012. Can you try in this format by getting rid of `html-content`

**Comment by shakum3012** [comment]
@shravan-balasubramanian @asifahmedfw Thanks for the explanation. Its works now.
