### ISSUE TITLE
[Bug] - Nesting tabs is not working

### ISSUE THREAD

**Issue by shakum3012** [freshworks/crayons#109]
**Component**
fw-tabs

**Describe the bug**
Creating nested tabs ie., child tab under a parent tab shows the child tab both as a child tab and also in the same level as the parent.

**To Reproduce**
Steps to reproduce the current behavior:
Run the below code
` <fw-tabs id="outertab">
        <fw-tab tab-header="outertab">
            <fw-tabs id="inner tab">
                <fw-tab tab-header="innertab"></fw-tab>
            </fw-tabs>
        </fw-tab>
    </fw-tabs>`

**Expected behavior**
The child tab shouldn't be shown parallel to the parent tab.

**Screenshots**

<img width="467" alt="Screenshot 2020-08-13 at 11 57 31 PM" src="https://user-images.githubusercontent.com/17592031/90172581-d974ef00-ddc0-11ea-805a-49654f5f3cae.png">

**Comment by asifahmedfw** [comment]
@shakum3012 This is expected. We have deliberately not added padding as we don't want developers to lose out on flexibility.
To do this, you can add a class to `fw-tab` and add a padding. It should work. 😄 
Closing this. Do let me know if you face any problems.

**Comment by asifahmedfw** [comment]
Problem is with nesting. Re-opening the issue.
