### ISSUE TITLE
[Feature Request] - Toast component to toast error, info messages

### ISSUE THREAD

**Issue by shravan-balasubramanian** [freshworks/crayons#111]
**Describe the functionality of the new component:**
Toast component that follows the Freshworks Design system

**More details:**
https://xd.adobe.com/view/a8299f86-4d90-40f9-4d23-7dc26f9266e3-de18/screen/682d63fb-750d-4462-b44c-3d6b1f347236/

[**Edit**] - @sathishkumar-thangavel 

### Description:
Toast component used to toast the success/failure/warning messages for span of few seconds or with close button. This is used to alert the user without completely disrupt the user workflow.

### Properties
Property | Attribute | Description | Type | Default
---------|----------|------------|-------|--------
type|type|toast message type(success/error/warning/inprogress)|string|warning
timeout|timeout|duration to show message(in ms)|number|2000
content|content|message to be displayed|string|none
actionLinkText|action-link-text|message of action link|string|none
sticky|sticky|won't close automatically|boolean|false
pauseOnHover|pause-on-hover|toast will not be closed while hovering|Boolean|true
position|position|position of the toast in screen(top-center/top-left/top-right)|string|top-center

### Events
Event | Description | Type
------|-------------|------
fwLinkClick|Emitted on action link click|customEvent

### Usage
`<fw-toast type="failure" sticky="false" timeout="5000"></fw-toast>`

`document.querySelector('fw-toast').trigger({type:'success',content:'Saved Successfully'});`

**Comment by asifahmedfw** [comment]
Looks Good. Can we also add a position: Left - Right - Top - Bottom?

**Comment by asifahmedfw** [comment]
Question:  How will someone trigger it?

**Comment by sathishkumar-thangavel** [comment]
@asifahmedfw Will update the usage/trigger flow in a while.

for comment on Position: I thought of set by default in top-center as shown in DSM.

**Comment by shravan-balasubramanian** [comment]
Also, can you clarify this 
Can the user declare one toast element and dynamically change the content also or should the dev declare it for each content and options? @sathishkumar-thangavel

**Comment by sathishkumar-thangavel** [comment]
@shravan-balasubramanian The user can declare one toast component and can change the content and options dynamically.
