### ISSUE TITLE
[Feature Request] - Dropdown button

### ISSUE THREAD

**Issue by shravan-balasubramanian** [freshworks/crayons#112]
**Describe the functionality of the new component:**
A dropdown  button according to the Design system found in 
https://xd.adobe.com/view/a8299f86-4d90-40f9-4d23-7dc26f9266e3-de18/screen/eb6930f3-3b16-49ee-9aaa-3dbc780e7154/

**More details:**
![Screenshot 2020-08-17 at 10 55 50 PM](https://user-images.githubusercontent.com/46365868/90425083-cde53900-e0dc-11ea-960f-937c5a4801fa.png)

### Properties
This will be part of fw-button itself
Property | Attribute | Description | Type | Default
---------|----------|------------|-------|--------
dropdown|dropdown|dropdown button or not|Boolean|false
split|split|Whether to split dropdown or not. Invalid if dropdown is false|Boolean|false
searchable|searchable|Whether the dropdown button should be searchable. Invalid if dropdown is false|Boolean|false
value|value|Selected options|Array|undefined
placeholder|placeholder|Placeholder for search input|String|''

### Events
Event | Description | Type
------|-------------|------
fwOptionClick|Emitted on selecting an option|customEvent
fwOptionsAdd|Emitted on adding options (`Add` button click)|customEvent

### Sample HTML
```html 
<fw-button dropdown split> Select OTT 
  <span id="1" value="netflix"> Netflix </span>
  <span id="2" value="amazon"> Amazon </span>
</fw-button>
```

**Comment by asifahmedfw** [comment]
Can you detail the options part with an example?

**Comment by shravan-balasubramanian** [comment]
<fw-button size="medium" dropdown options = [
{
id: '1',
label: 'Netflix',
value: 'Amazon'
},
{
id: 2,
label: 'Amazon',
value: 'Amazon'
}
]

@asifahmedfw

**Comment by shravan-balasubramanian** [comment]
@asifahmedfw Can you re-review this and the PR
