### ISSUE TITLE
[Enhancement] - Edit Documentation and Markdown files for Grammer, Spelling, Typos, and Uniformity

### ISSUE THREAD

**Issue by lax0248917** [freshworks/crayons#116]
**Description of the enhancement:**
I would love to begin contributing by proofreading and editing the documentation and markdown files for typos, spelling mistakes, grammatical errors, and word uniformity

**Describe the solution you'd like**
Clear and concise communication is key in documentation. This will help alleviate any confusion, offer a uniformed document, and present a professional and finished product for the developer community.

ex. Found in CONTRIBUTING.md  
![image](https://user-images.githubusercontent.com/48189365/91314908-1065e000-e785-11ea-90d4-fe15d70cc812.png)

ex. Found in Documentation for Checkbox (one spelled "checkbox" the other "check box")
![image](https://user-images.githubusercontent.com/48189365/91315094-40ad7e80-e785-11ea-92fc-d3fee9776357.png)

None of these are huge issues, but I am new to open source and I see this as a great way for me to get involved.

Thank you

-Zach

**Comment by asifahmedfw** [comment]
@lax0248917 That would be great! Assigning this to you. 😄

**Comment by lax0248917** [comment]
@asifahmedfw Thank you! Is best practice to create a new branch off of my forked repo? I did not see this step in the contribution guidelines.

**Comment by asifahmedfw** [comment]
@lax0248917 Contributors are open to using any method they deem fit. They can use the `next` branch itself. Although, it is easier to have your own branch in a forked repo. This makes it easier for rebasing with the main repo.
