### ISSUE TITLE
[Bug] - fwChange event handler function attached to fw-tabs is being fired for fw-select as well

### ISSUE THREAD

**Issue by samuelpares** [freshworks/crayons#120]
**Component**
fw-tabs and fw-select

**Describe the bug**
Both fw-tabs and fw-select has the event fwChange.
When a change happens in fw-select, the event handler function attached for fw-tabs is being fired.
Even if the fw-select has it's on function attached.

**To Reproduce**

```
<html>
<body>
  <fw-tabs id='tabs-settings'>
    <fw-tab tab-header="Tab 1">
      <fw-select id="slt-numbers">
        <fw-select-option value="1">Test</fw-select-option>
      </fw-select>
    </fw-tab>
  </fw-tabs>
</body>
</html>
```

```
$(document).ready(function () {
  app.initialized().then(function (_client) {
    $("#tabs-settings").on("fwChange", fwTabsOnChange);
    $("#slt-numbers").on("fwChange", fwSelectOnChange);
  });
});

function fwSelectOnChange() {
  console.log("fwSelectOnChange")
}

function fwSelectOnChange() {
    console.log("fwSelectOnChange")
}
```

When selecting an item in the fw-select, both event handler functions are fired.

**Expected behavior**
fw-select should not fire the event handler function attached to fw-tabs

**Comment by asifahmedfw** [comment]
Hey @samuelpares, 👋 

Web components work just like HTML elements. When an event is emitted from a child element, it propagates up the DOM tree. As the above example has event handlers with the same name, both of them are triggered when an event is triggered in the child.
To prevent this, you can use `event.stopPropogation()` in the event handler. So, the modified code sample would look something like this:
```
$(document).ready(function () {
  app.initialized().then(function (_client) {
    $("#tabs-settings").on("fwChange", fwTabsOnChange);
    $("#slt-numbers").on("fwChange", fwSelectOnChange);
  });
});

function fwSelectOnChange(event) {
  event.stopPropagation(); // This will stop it from propagating further.
  console.log("fwSelectOnChange")
}

function fwTabsOnChange() {
    console.log("fwSelectOnChange")
}
```

Hope this solves the issue. Please do get back on whether this works for you 😄

**Comment by samuelpares** [comment]
Oh man, It worked. 
I did not know about that.
Sorry for the trouble hehe
