### ISSUE TITLE
[Enhancement] - Expose `text` in fw-select

### ISSUE THREAD

**Issue by asifahmedfw** [freshworks/crayons#125]
**Description of the enhancement:**
Create a property to expose the selected Text for `fw-select`.

**Describe the solution you'd like**
Currently, we only expose the value via the `value` property. We can have another property called `text` that exposes the selected text to the user.
https://crayons.freshworks.com/components/select/#properties

**Comment by narendran-kannan** [comment]
Would like to work on this! @asifahmedfw

**Comment by asifahmedfw** [comment]
@narendran-kannan Assigned this to you.

**Comment by samuelpares** [comment]
Any update on this? Very expected this enhancement 😁

**Comment by narendran-kannan** [comment]
Will update this weekend :)

**Comment by samuelpares** [comment]
Was it released? I didn't find any update on documentation..

**Comment by asifahmedfw** [comment]
@samuelpares Sorry, there haven't been any updates to this yet. 😞 
@narendran-kannan I believe this got lost on your radar! Any updates on this? Please do let me know if you no longer want this to be assigned to you. 😄

**Comment by samuel-loupen** [comment]
And about now? Any news?

**Comment by kishore-kumar-E3682** [comment]
During selection fw-select will emit the fwChange event which can be consumed to get the text. 
For example:
```javascript
methodOptionSelect.addEventListener('fwChange', (e) => {
    console.log(e.detail.selectedOptions);
  });
```
here `selectedOptions` is an array of object (for both single and multi select) which corresponds to the selected options. `selectedOptions[0].text` will provide you the first selected options text.
