### ISSUE TITLE
[Enhancement] - Set Values to fw-select with mulitple option.

### ISSUE THREAD

**Issue by ghost** [freshworks/crayons#132]
**Description of the enhancement:**

Adding an additional method to the `<fw-select> </fw-select>` component. In order to set values for `fw-select` component with `multiple` property, we need a out of box method from FW. Currently, we are manipulating the value of the select element using array methods and re-rendering the `fw-select` component to DOM.

**Describe the solution you'd like**

We would like to have a method to set values to `fw-select` component. Like `getSelectedItem() => Promise<any>` available for extract values.

**Comment by narendran-kannan** [comment]
I would like to work on this, Kindly assign this to me!
@itzarshath @asifahmedfw

**Comment by asifahmedfw** [comment]
Assigning this to you @narendran-kannan ! Will be looking forward for your PR!
