### ISSUE TITLE
[Feature Request] - Adding a collapse component

### ISSUE THREAD

**Issue by subbu-muthusubramanian** [freshworks/crayons#141]
**Description**

_Collapse_ - Used to toggle the visibility of content 

**Use Case**

Lets say a website shows a list of recipes. When a user selects a recipe, the ingredients of that recipe will be visible to the user.

It is similar to **Tabs** but the only difference is that tabs will always show content of a tab by default. 

**More details:**
Screenshots taken from Bootstrap 4:
<img width="1084" alt="Screenshot 2020-10-10 at 12 40 16 PM" src="https://user-images.githubusercontent.com/56425223/95648699-0b6fac80-0af7-11eb-9957-2fe3619a4b05.png">
<img width="1077" alt="Screenshot 2020-10-10 at 12 40 01 PM" src="https://user-images.githubusercontent.com/56425223/95648710-1cb8b900-0af7-11eb-9813-05845728ce9d.png">

**Comment by Saif-Shines** [comment]
We bought in accordions on the latest release of crayons.

You can find it here: https://crayons.freshworks.com/components/core/accordion/
