### ISSUE TITLE
[Bug] - fw-icon doesn't work in a Vue application

### ISSUE THREAD

**Issue by shravan-balasubramanian** [freshworks/crayons#143]
**Component**
`fw-icon`

**Describe the bug**
Icon component does not work in Vue app( or anywhere else I guess! ), since it tries to fetch the icon.svg from the current web app and from the component library

**To Reproduce**
* Include <fw-icon> component in the vue app 
* Icon component is not displayed
* Go to networks tab and search for the icon name (  e.g `add-contact` if the html you included is `<fw-icon name="add-contact" size="18" color="green"></fw-icon>`)
* [This line](https://github.com/freshworks/crayons/blob/89a80f09c1c2c7b01693dbbfef5f4cee6b964253/src/components/icon/icon.tsx#L28) tries to fetch from that current server and does not return svg, probably because of https://github.com/ionic-team/stencil/issues/2269

**Expected behavior**
Icon should be displayed

**Screenshots**
![Screenshot 2020-10-12 at 10 47 47 PM](https://user-images.githubusercontent.com/46365868/95773882-f5bbdc00-0cdc-11eb-91a1-c811be19dee2.png)
![Screenshot 2020-10-12 at 10 46 20 PM](https://user-images.githubusercontent.com/46365868/95773773-c1e0b680-0cdc-11eb-98bf-8d98373379ca.png)

**Comment by existentialcoder** [comment]
I will pick this up @asifahmedfw
