### ISSUE TITLE
fw-icon search color is not changing 

### ISSUE THREAD

**Issue by DineshKumarRavichandran** [freshworks/crayons#147]
**Component**
fw-icon
name = "search"

**Describe the bug**
search icon color is not changing

**To Reproduce**
Use the following line:
`<fw-icon name="search" color="white"></fw-icon>`

Icon Colors are getting changing except for search icon

**Screenshots**
![image](https://user-images.githubusercontent.com/42378033/98523538-0b9ccc80-229c-11eb-91cb-ba148f218d85.png)

**Comment by asifahmedfw** [comment]
This is a bug on our side. We will fix it soon.
