### ISSUE TITLE
Dropdown value is not displayed after choosing option value

### ISSUE THREAD

**Issue by DineshKumarRavichandran** [freshworks/crayons#148]
**Component**
Dropdown button (fw-dropdown-button)

**Describe the bug**
Usually after choosing the value from a dropdown, the value should display there. But in fw-dropdown-button, the value in option tag is not replaced the fw-dropdown-button label.

**To Reproduce**
Steps to reproduce the current behavior:

1. Go to https://crayons.freshworks.com/components/dropdown-button/#usage
2. Click on any dropdown and choose the value 
3. The value will not replace the label of fw-dropdown-button

**Expected behavior**
After choosing the value in the dropdown the value must be changed to new one.

**Screenshots**
![image](https://user-images.githubusercontent.com/42378033/99490041-04a64600-298f-11eb-8913-48fbc0dcb90d.png)

**Comment by asifahmedfw** [comment]
@DineshKumarRavichandran I am sorry, but the component is not designed for that use case. A dropdown is used as a menu.

If you are looking for a select, a multi-select is what you need.

Please check https://crayons.freshworks.com/components/select/ for more details. Closing this for now.
