### ISSUE TITLE
[Enhancement] - Ability to id and class to fw-select-option

### ISSUE THREAD

**Issue by Raj-Mahesh** [freshworks/crayons#155]
**Description of the enhancement:**
Requesting the ability to add class and id to fw-select-option, just like in fw-select.

**Describe the solution you'd like**
I would just like to be able to add id and class to the fw-select-option as I want to trigger changes to that particular dropdown option based on certain conditions. (For example, having two dropdown boxes, and disabling the option, which has been selected in the first dropdown box, in the second dropdown box.)

Functionality like this: As you can see that I have selected status in the first dropdown, it has been disabled in the second dropdown. This can be achieved if i can add classes and id to the fw-select-option.
![image](https://user-images.githubusercontent.com/41161698/101236705-5eca3980-36f9-11eb-8023-27baf27b0d6e.png)

**Comment by kishore-kumar-E3682** [comment]
@Raj-Mahesh The data source of the select can be modified dynamically in crayons V3, with this you can set the options disabled on the second selected based on the first select. An example is shown here https://codesandbox.io/s/zen-cdn-znc4qi?file=/src/index.js
