### ISSUE TITLE
Lookup for drop downs requires users to type two characters before the search is triggered. 

### ISSUE THREAD

**Issue by barncliff** [freshworks/crayons#173]
**Description of the enhancement:**
A user needs to know the values in a lookup entity to be able to type the first two characters. It would be helpful to provide a workaround for new users. 

**Describe the solution you'd like**
Either provide a wildcard option for drop downs perhaps limiting the number of returned values to minimise performance risk or add a default link to view source data in the referenced table.

**Comment by asifahmedfw** [comment]
@barncliff Can you pinpoint the web components in the library that have this behavior? A screenshot/screengrab would be great too!

**Comment by barncliff** [comment]
All Lookup fields operate this way e.g. Contact lookup to Account.
You click on the dropdown arrow to get a box which says 'Type to search'.
![image](https://user-images.githubusercontent.com/66131645/107277759-ca5bba80-6a4c-11eb-964f-a415a3295813.png)

**Comment by asifahmedfw** [comment]
I am guessing you are on the wrong repo 🤔

**Comment by barncliff** [comment]
The issue is in Freshworks CRM

**Comment by asifahmedfw** [comment]
@barncliff This library is not used inside Freshworks CRM. I have communicated your feedback to Freshworks CRM team. Closing this here.
