### ISSUE TITLE
Make 'current date' available for formulas used in calculated fields

### ISSUE THREAD

**Issue by barncliff** [freshworks/crayons#174]
**Description of the enhancement:**
Formulas aren't able to calculate Age i.e. period of time between a given date (Date of Birth) and Today.

**Describe the solution you'd like**
Allow calculated fields to include formulas that reference a 'today's date' variable, which can be used to calculate 'Age' in years/months/days. This would need a daily automated update as I understand calculated fields are only updated when the source field is updated. This functionality is available in Dynamics.

**Comment by asifahmedfw** [comment]
This is not related to Crayons. Closing this.
