### ISSUE TITLE
[Bug] - Not able to edit text search in fw-select

### ISSUE THREAD

**Issue by sunnynk19** [freshworks/crayons#175]
**Component**
fw-select

**Describe the bug**
backspace not deleting characters after an option is selected

**To Reproduce**
1. Click on fw-selects
2. Select any one option.
3. Now again click on fw-select and try searching for other keyword after deleting the existing text

**Expected behavior**
It should clear the text and reset the dropdown suggestion based on the new text

**Comment by kishore-kumar-E3682** [comment]
Fixed in version 3 - can be checked over here https://crayons.freshworks.com/components/core/select/
