### ISSUE TITLE
[Bug] - Icon not aligned to middle in fw-input icon

### ISSUE THREAD

**Issue by itizarsa** [freshworks/crayons#183]
**Component**
fw-input 

**Describe the bug**
When I use the fw-input component with the icon-left property, the icon is not aligned to the middle of the input box. When I checked the element styles in dev tools, the padding to the icon is given as 3px 0 0 6px. So I tried changing the padding of the icon to 6px on top, then the icon aligned to the middle of the input box.

**To Reproduce**
Simply using the fw-input component will reproduce this.

**Expected behavior**
We expect the icon to be aligned to the middle of the input. I believe that's how it was done previously.

**Screenshots**

Default padding :

<img width="306" alt="default" src="https://user-images.githubusercontent.com/77574889/112168818-a11b7600-8c17-11eb-845f-200738a28e5a.png">

Modified Padding :

<img width="306" alt="modified" src="https://user-images.githubusercontent.com/77574889/112168888-b2fd1900-8c17-11eb-85b2-9348341237ac.png">

**Comment by asifahmedfw** [comment]
@itizarsa 

I don't see a problem based on the usage.
https://codesandbox.io/s/unruffled-euclid-f8qi8?file=/index.html

Can you check it out?

**Comment by itizarsa** [comment]
@asifahmedfw 

I found the issue. If we add the Bootstrap CDN, it breaks the icon alignment. Find the code [here](https://codesandbox.io/s/bold-violet-lkuhm)

**Comment by asifahmedfw** [comment]
I think this is because bootstrap adds a line-height:1.5

Can you override that to line-height: 1 in your app and see if that works?

**Comment by asifahmedfw** [comment]
Closing this issue for now. Please re-open if you still need help with the above.

**Comment by itizarsa** [comment]
@asifahmedfw  Changing line-height: 1 doesn't change the behavior. Some other styling affecting the icon.
