### ISSUE TITLE
[Bug] - Using URL variable within js throws TypeError

### ISSUE THREAD

**Issue by Saif-Shines** [freshworks/crayons#187]
**Component**
All comments are effected

**Describe the bug**
In the HTML page where Crayons UI components are rendered, if the `.js` associated with it is having a `var URL = `` this needs to be template literal `` ` declaration, `crayons.esm.js` throws TypeError as follows

```sh
p-7a09e628.js:1 Uncaught TypeError: URL is not a constructor
    at Re (p-7a09e628.js:1)
    at crayons.esm.js:1
```

**To Reproduce**

1. Have a HTML page
2. Declare ` var URL = `` this is a template string `` `
3. See crayons.esm.js throwing an error

Sample code - https://jsbin.com/kuqamafeba/edit?html,js,output

**Comment by asifahmedfw** [comment]
Hi @Saif-Shines 
URL is a native function as part of Web API - https://developer.mozilla.org/en-US/docs/Web/API/URL
Can you use a different name and check whether you have the same problem?

**Comment by Saif-Shines** [comment]
Haven't realised `URL` is a web API. Thanks for pointing that out. I will close this issue.

> Can you use a different name and check whether you have the same problem?
It doesn't appear to be a problem, that way. :-)
