### ISSUE TITLE
[Enhancement] - searchable select component

### ISSUE THREAD

**Issue by Saif-Shines** [freshworks/crayons#188]
**Description of the enhancement:**
As soon as `searchable` attribute is added in dropdown component, the component by default assumes an checkbox oriented dropdown.

**Describe the solution you'd like**
I wish if there was an attribute to either have it has checkbox or not have it as checkbox. For the lists of items those are over ~50 items and want to select single item, it would be nice if only search + single select item is possible.

**Comment by kishore-kumar-E3682** [comment]
Search with single select is now available in V3 via fw-select and fw-list-options components - https://crayons.freshworks.com/components/core/select/
