### ISSUE TITLE
[Bug] - Datepicker, not able to set minDate and maxDate via javascript

### ISSUE THREAD

**Issue by nithin-raj** [freshworks/crayons#189]
**Component**
Datepicker

**Describe the bug**
When we set minDate or maxDate via javascript, the component is not updating.

**To Reproduce**
1,Create a Datepicker component and execute the following jquery command, $("#daterange").attr("maxDate", "20-Apr-2021").

**Expected behavior**
The component should limit the user to the maxDate provided earlier.

**Comment by shravan-balasubramanian** [comment]
Hey @nithin-raj, just to confirm. Did you try `max-date` instead of `maxDate`? Attributes usually are `-` separated

**Comment by nithin-raj** [comment]
Hi @shravan-balasubramanian both options didn't work.

**Comment by Saif-Shines** [comment]
@nithin-raj We are hoping the new crayons release might have solved this. Can you please confirm?

https://crayons.freshworks.com/components/core/datepicker/#demo

**Comment by santhoshbalusamy** [comment]
@Saif-Shines it is not working

**Comment by arvindanta** [comment]
This is addressed as part of https://www.npmjs.com/package/@freshworks/crayons/v/3.6.0-beta.1
