### ISSUE TITLE
[Feature Request] - Grids / Layouts

### ISSUE THREAD

**Issue by hemchander23** [freshworks/crayons#191]
A default grid system offered by Crayons for positioning components. Ideally, it would be great if there were pattern recommendations based on different placeholder locations

**More details:**
- https://getbootstrap.com/docs/4.0/layout/grid/

**Comment by Saif-Shines** [comment]
With latest crayons@v3 release CSS Layouts have been added - https://crayons.freshworks.com/css-utils/layout/
