### ISSUE TITLE
[Feature Request] - Wizards

### ISSUE THREAD

**Issue by hemchander23** [freshworks/crayons#192]
A UI component that allows step-wise progress. Ideally for Installation pages and Full-page apps. 

**More details:**
- https://material-ui.com/components/steppers/
- https://material.io/archive/guidelines/components/steppers.html#steppers-types-of-steppers (Horizontal Stepper)

**Comment by Saif-Shines** [comment]
We bought in progress loader that is equivalent of this. :) 

https://crayons.freshworks.com/components/core/progress-loader/

Closing this issue.
