### ISSUE TITLE
[Enhancement] - Date and Time picker

### ISSUE THREAD

**Issue by hemchander23** [freshworks/crayons#195]
**Description of the enhancement:**
- Fix rendering bugs
- UI corrections for month field
- Test for responsiveness

**Comment by sabatale** [comment]
@hemchander23 Would that be a component covering both date and time selection in a calendar view?

I was not able to find it in the docs.

Something like:

![image](https://user-images.githubusercontent.com/50220345/143136865-b52a7d99-420a-42be-bd71-adcb348a9395.png)

**Comment by kulkarni-kashyap** [comment]
This is addressed as part of https://www.npmjs.com/package/@freshworks/crayons/v/4.0.0.
