### ISSUE TITLE
[Enhancement] - More Icons

### ISSUE THREAD

**Issue by hemchander23** [freshworks/crayons#197]
**Description of the enhancement:**
More icons can be added to the list of icons offered by Crayons. It would help if these icons are reusable and part of the Freshworks product itself.

**Comment by kishore-kumar-E3682** [comment]
From crayons V3 you can import you favourite icon pack into crayons and consume it via fw-icons. Please refer this doc more information - https://crayons.freshworks.com/components/core/icon/#fwicon-as-a-renderer-for-external-lib-icons

**Comment by kishore-kumar-E3682** [comment]
@hemchander23 did you get a change to try the above mentioned feature.

**Comment by kishore-kumar-E3682** [comment]
@hemchander23 closing this issue since its inactive.
