### ISSUE TITLE
[Bug] - onChange event is not working for Input, DatePicker and other components

### ISSUE THREAD

**Issue by ikismail** [freshworks/crayons#203]
Hi guys while surfing web I got to know about Crayons, and I'm really excited to use in my demo application to know how it will work with React application. while doing that I faced few issues. the documentation asked to use fwClick, fwChange and so on. but it doen't works. instead of fwClick -  onClick works but for onChange or fwChange is not working.

**Describe the bug**

onChange event is not working for Input, DatePicker, Select and other Form Components, I created a workaround in JSFiddle for all the components here [JSFiddle link](https://jsfiddle.net/ikismail7/4apdxvck/35/) 

Did I miss anything or is there any other way ? 

**Screenshots**
![image](https://user-images.githubusercontent.com/17190913/125728029-3bc85950-a364-4300-a130-77337a7b729e.png)

**Comment by asifahmedfw** [comment]
Hey @ikismail ,
Thanks for trying out Crayons!

Crayons is based on web components.

While web components are supposed to work everywhere, the traditional way of adding event listners does not work with React.

> Because React implements its own synthetic event system, it cannot listen for DOM events coming from Custom Elements without the use of a workaround. Developers will need to reference their Custom Elements using a ref and manually attach event listeners with addEventListener. This makes working with Custom Elements cumbersome.

Source: https://custom-elements-everywhere.com/

You can use [useRef](https://reactjs.org/docs/hooks-reference.html#useref) to solve this or just use refs as mentioned here -> https://vaadin.com/learn/tutorials/using-web-components-in-react

**Comment by ikismail** [comment]
> Hey @ikismail ,
> Thanks for trying out Crayons!
> 
> Crayons is based on web components.



@asifahmedfw Thank you bro. I'll try to implement using manual event listeners.
