### ISSUE TITLE
[Bug] - Issue in Datepicker (fw-datepicker)

### ISSUE THREAD

**Issue by Clement-Franklin** [freshworks/crayons#242]
**Component**
Datepicker (fw-datepicker)

**Describe the bug**
Few characters in month and year selection dropdown in fw-datepicker are displayed in the next line (works on mobile but not on PC!)

**Screenshots**
![image](https://user-images.githubusercontent.com/60420245/137780113-cd881cfc-e2e2-49d9-a977-e43e8310311f.png)

![image](https://user-images.githubusercontent.com/60420245/137780150-888bf9df-456c-4ef2-b199-0b1dfafab2c7.png)

**Comment by kishore-kumar-E3682** [comment]
@Clement-Franklin this issue is fixed in V3 - https://crayons.freshworks.com/components/core/datepicker/

**Comment by Clement-Franklin** [comment]
Thanks for the update @kishore-kumar-E3682. Closing the issue.
