### ISSUE TITLE
[Bug] - Crayons fw-select - setting disabled attribute to false does not enable the drop down options as well

### ISSUE THREAD

**Issue by essencient** [freshworks/crayons#375]
**Component**
fw-select

**Describe the bug**
Setting disabled attribute to false does not enable the drop down options as well

**To Reproduce**
See see this [jsFiddle](https://jsfiddle.net/fae41nb7/9)

**Expected behavior**
Setting disabled attribute on fw-select does not change disabled attribute of children.

**Comment by essencient** [comment]
Any news on when this will be fixed?

**Comment by santhoshbalusamy** [comment]
can you please assign this to me?
@asifahmedfw

**Comment by kishore-kumar-E3682** [comment]
This issue is fixed in V3  https://github.com/freshworks/crayons/pull/501
