### ISSUE TITLE
[Enhancement] - Support for getting current values in `fw-form`

### ISSUE THREAD

**Issue by shravan-balasubramanian** [freshworks/crayons#613]
**Description of the enhancement:**
- There is no straight forward way now to get the current state values of the form when using `fw-form`
- The two hacky ways that I see are to listen to a `validate` method to get the values or do a `doSubmit` to get the values.
- There should be a method exposed publicly by the component to get the current values of the form. 
- This will be useful to modify the form schema dynamically based on the dependant field values
- Or if there is another way to dynamically change form schema during JS framework runtime, that would also be great

**Describe the solution you'd like**
- Ideally a `getValues` method exposed publicly
- Code
``` js
const values = await formRef.getValues();
```

**Comment by kulkarni-kashyap** [comment]
This is addressed as part of https://www.npmjs.com/package/@freshworks/crayons/v/3.6.0-beta.0
