### ISSUE TITLE
[Enhancement] - Date-time-picker

### ISSUE THREAD

**Issue by shravan-balasubramanian** [freshworks/crayons#616]
**Description of the enhancement:**
- Do we have an option to render the date time picker
- With the docs I can only find them as two separate components

**Describe the solution you'd like**
A clear and concise description of what has to happen. It can be validated by the repository maintainers and voted by the contributors.

- Something like a `fw-date-time-picker`
- Not sure if that can be expandable with the existing components. That's why added as an enhancement

🔗  [Reference from element-ui](https://element.eleme.io/#/en-US/component/datetime-picker)

**Comment by kulkarni-kashyap** [comment]
@shravan-balasubramanian , this component is available as part of https://www.npmjs.com/package/@freshworks/crayons/v/4.0.0 as a variant in `fw-datepicker` component
