### ISSUE TITLE
[Bug] - Not able to modify the height of the fw-select Component.

### ISSUE THREAD

**Issue by sarveswaran-ramanathan** [freshworks/crayons#620]
**Component**
fw-select

**Describe the bug**
Not able to scroll completely as the height over flows for the component **fw-select**

**To Reproduce**
Steps to reproduce the current behavior:

<fw-select  id="id"
                    label="label"
                    required="true"
                    allow-deselect="false"
                    placeholder="placeholder"
                    error-text="error-text"
                    state="normal"
>

Add more than 30 options the height will overflow and we will not able to scroll completely.
Please note that we are rendering this inside an iframe

**Screenshots**
<img width="1440" alt="Screenshot 2022-06-08 at 2 03 13 PM" src="https://user-images.githubusercontent.com/81422825/172577822-002a5b0b-a37f-49bc-a887-3291f47da496.png">

**Comment by srivalli-sivaramasankaran** [comment]
Hi @sarveswaran-ramanathan , Can you please try the custom css property, `--fw-popover-max-height` to modify the height of the options container ?

**Comment by sarveswaran-ramanathan** [comment]
Hi @srivalli-sivaramasankaran this fixed the issue. Thanks.
