### ISSUE TITLE
[Bug] - fw-datepicker with range mode and with getValue return invalid time value

### ISSUE THREAD

**Issue by santhoshbalusamy** [freshworks/crayons#648]
**Component**
fw-datepicker with range mode

**Describe the bug**
When we tried to get the value, ie using element.getValue().then(console.log);
it is returning **RangeError: Invalid time value**

**To Reproduce**
Steps to reproduce the current behavior:
1. Add the Date picker with the mode of range
2. Add the change event for that date picker
3. on that change event, try to get the value by element.getValue().then(console.log);
4. it will throw the error
5.

**Expected behavior**
A clear and concise description of what is expected to happen.
it will return the correct value

**Screenshots**
If applicable, add screenshots to help explain the issue.

<img width="627" alt="image" src="https://user-images.githubusercontent.com/23396872/180836919-9538eb7f-d06c-45df-8a12-2738e0ac6b42.png">

**Additional context**
Add any other context about the bug here.

**Comment by kulkarni-kashyap** [comment]
This is being taken care as part of https://github.com/freshworks/crayons/pull/650

**Comment by arvindanta** [comment]
This is addressed as part of https://www.npmjs.com/package/@freshworks/crayons/v/3.6.0-beta.1
