### ISSUE TITLE
[Enhancement] - fw-datepicker need option to disabled

### ISSUE THREAD

**Issue by santhoshbalusamy** [freshworks/crayons#649]
**Description of the enhancement:**
need an option to disable the date-picker component
similar to other input components, it is not possible to disable this component,

**Describe the solution you'd like**

eg: `<fw-datepicker value="2021-12-02" display-format="dd-MM-yyyy" disabled></fw-datepicker>`

this should disable/read-only mode of that component

**Comment by kulkarni-kashyap** [comment]
This is being taken care as part of https://github.com/freshworks/crayons/pull/651

**Comment by arvindanta** [comment]
This is addressed as part of https://www.npmjs.com/package/@freshworks/crayons/v/3.6.0-beta.1
