### ISSUE TITLE
[Bug] - Timepicker format HH:mm is ignored throws rangeError

### ISSUE THREAD

**Issue by jimmyhchan** [freshworks/crayons#662]
**Component**
Timepicker (React component)

**Describe the bug**
`<FwTimepicker format="HH:mm" />` throws a RangeError
`<FwTimepicker format="HH:mm" minTime="00:00" maxTime="23:30" />` ignores the format `HH:mm` provided

**To Reproduce**
Steps to reproduce the current behavior:
https://codesandbox.io/s/crayons-timepicker-r71tuw

**Expected behavior**
* minTime and maxTime props should be optional per docs
* format `HH:mm` should display non-meridian options

**Comment by arvindanta** [comment]
@jimmyhchan The issue has been fixed in version `@freshworks/crayons@4.0.0-beta.8` .
