### ISSUE TITLE
[Bug] - Text Area width is differ from chrome and firefox

### ISSUE THREAD

**Issue by santhoshbalusamy** [freshworks/crayons#663]
**Component**
fw-textarea

**Describe the bug**
if we set the width of the text area by using colums, it is differ from firefox and chrome

**To Reproduce**
https://crayons.freshworks.com/components/core/textarea/#demo

open the above in both firefox and chrome to see the difference.

**Expected behavior**
In both browsers, width should be same

**Screenshots**
If applicable, add screenshots to help explain the issue.

in chrome:

<img width="998" alt="image" src="https://user-images.githubusercontent.com/23396872/185983971-37a9e9d3-f0b2-4694-9bb6-8b76023a27b0.png">

In firefox:

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/23396872/185984035-58494988-5b7f-4b21-a251-e1fb7a525f36.png">

**Additional context**
NA

**Comment by arvindanta** [comment]
@santhoshbalusamy Can you try `@next` version of crayons and use the below css variables to set the min height and width of the textarea to ensure cross browser compatibility.

`--fw-textarea-min-height | Min-Height of the textarea`.
`--fw-textarea-width | Width of the textarea.`
