### ISSUE TITLE
Release artifacts on other CDNs like CDNJS and jsDelivr

### ISSUE THREAD

**Issue by Thirumalai** [freshworks/crayons#711]
The recent versions of crayons are currently only available on unpkg.com. One of our apps used components from the crayons library and became useless when unpkg.com's servers went down. 

Please consider publishing release artifacts on other CDNs like CDNJS and jsDelivr as well so that we can use a better alternative if unpkg.com is unstable.

**Comment by Thirumalai** [comment]
https://github.com/mjackson/unpkg/issues/343

**Comment by p-ob** [comment]
This library publishes to npm, and not directly to unpkg. I believe you can already use alternative CDNs as long as those CDNs support npm as a repository for packages. 

For example. with jsDelivr: https://cdn.jsdelivr.net/npm/@freshworks/crayons@2.13.4/dist/index.js

**Comment by Thirumalai** [comment]
Thanks for the clarification! I got confused by the version number on jsDeliver.
