### ISSUE TITLE
[Bug] - settings icon has it's own custom fill color instead of inheriting color from parent

### ISSUE THREAD

**Issue by prasanna-vijayan** [freshworks/crayons#791]
**Component**
Icon

**Describe the bug**
SVG of the settings icon has it's own fill color instead of inheriting color from parent 

**To Reproduce**
Steps to reproduce the current behavior:

1. Download the latest version
2. use `<FwIcon name="settings" />` in react
3. the default color of the icon is #264966 instead of "currentColor"

**Expected behavior**
It should adapt the color being used in the parent

**Screenshots**
<img width="75" alt="Screenshot 2023-02-07 at 6 39 36 PM" src="https://user-images.githubusercontent.com/58469402/217253695-08a747cb-3e69-401f-922f-577096234464.png">

**Comment by prasanna-vijayan** [comment]
I'll work on this.

**Comment by arvindanta** [comment]
The fix is available in @freshworks/crayons@4.2.0-beta.1 (next) dist-tag
