### ISSUE TITLE
[Bug] - Settings icon overlap the action column in fw-data-table

### ISSUE THREAD

**Issue by cnitish10** [freshworks/crayons#807]
**Component**
 fw-data-table
<img width="879" alt="Screenshot 2023-02-24 at 3 40 18 PM" src="https://user-images.githubusercontent.com/119387719/221531190-dfde6b6d-10dd-480c-a1ab-c1e3d9f17c19.png">

**Describe the bug**
RowActions in fw-data-table component, if I have only one row action, and if I enable the table settings, the settings icon overlaps the Actions column name

**Expected behavior**
its should not overlap on action column name

**Comment by Vignesh-Manogar-E3433** [comment]
Hi, we have added a property to data-table 'rowActionsWidthProperties' to address this issue from Crayons [version '4.2.0-beta.7'](https://unpkg.com/@freshworks/crayons@4.2.0-beta.7/dist/crayons/crayons.js). Adding codesandbox link below.

```js
datatable.rowActionsWidthProperties = {
  "min-width": "100px"
}
```

[![Edit adoring-babycat-orqhu0](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/adoring-babycat-orqhu0?fontsize=14&hidenavigation=1&theme=dark)
