### ISSUE TITLE
[Bug] - fw Date Picker in Fw Form is not considering getTimezoneOffset while showing the data for the data of format string = '2023-04-13'

### ISSUE THREAD

**Issue by harshith-venkatesh-freshworks** [freshworks/crayons#843]
**Component**
fw-date-picker

**Describe the bug**
User has observed the issue where for different timezones, date picker shows different view

**To Reproduce**
Steps to reproduce the current behavior:

1. System time needs to be changed to ensure to see different date for same data

**Expected behavior**
- Should offset be handled for string data in fw-date-picker or it needs to be handled in product

**Screenshots**
<img width="1792" alt="Screenshot 2023-04-13 at 2 10 20 AM" src="https://user-images.githubusercontent.com/96039290/231727573-a2cc7bf9-0427-4ccf-92b9-9aa2a1d4251c.png">

<img width="1792" alt="Screenshot 2023-04-13 at 3 42 17 PM" src="https://user-images.githubusercontent.com/96039290/231728025-007abc82-1598-428e-a74e-2f646fb9f02b.png">

**Additional context**
Add any other context about the bug here.

**Comment by arvindanta** [comment]
@srivalli-sivaramasankaran @harshith-venkatesh-freshworks can this be closed ?

**Comment by srivalli-sivaramasankaran** [comment]
This has been fixed.

**Comment by harshith-venkatesh-freshworks** [comment]
Thanks @srivalli-sivaramasankaran , for taking this bug on priority and resolving the issue.
We are currently able to see the issue being resolved in the Edit-Form of our application attaching both pics (before-after)

<img width="1792" alt="Screenshot 2023-04-27 at 10 43 49 PM" src="https://user-images.githubusercontent.com/96039290/235074930-ebc5469f-953e-4c35-99d5-3ab011c1ad15.png">

<img width="1792" alt="Screenshot 2023-04-27 at 10 47 49 PM" src="https://user-images.githubusercontent.com/96039290/235074865-06c3f83b-60ce-4fa6-9d9a-6b9dfccf3a13.png">
