### ISSUE TITLE
[Enhancement] - Improve keyboard accessibility for components.

### ISSUE THREAD

**Issue by MrRobz** [freshworks/crayons#87]
**Description of the enhancement:**
For components: checkbox, date picker, radio, Select. It would be wonderful if we could add keyboard navigation as well. Eg tick checkbox on entering, navigating Select dropdown list with keyboard and entering etc...
It would improve usability as well.

**Describe the solution you'd like**
Add keyboard watch events and when element active and key pressed, modify the component states.

**Comment by asifahmedfw** [comment]
We will bring in keyboard controls soon. Meanwhile if you are interested and motivated you can build the feature for one of the components and send us the PR 😊

**Comment by arpancodes** [comment]
Hello there,
Is anyone working on this issue? I want to try it for this Hacktoberfest. Please let me know if I can start working on it :)
Thanks in advance

**Comment by asifahmedfw** [comment]
Hey @arpancodes !
Thanks for your interest 😄 
This issue is open and you can definitely help by contributing! Assigning this to you.

**Comment by arpancodes** [comment]
Thanks 😄

**Comment by asifahmedfw** [comment]
@arpancodes Are you still working on the issue? Do let us know if you need any help. 😄

**Comment by kishore-kumar-E3682** [comment]
All input the components are keyboard accessible in crayons V3.
