### ISSUE TITLE
[Bug] - Strange styles in the Select component, and the popup doesn't open

### ISSUE THREAD

**Issue by taraschuiko** [freshworks/crayons#872]
**Component**
Select, FormControl (type DROPDOWN)

**Describe the bug**
The Select component has strange styles (border, margin: auto, etc.) and it throws "this.popover.show is not a function" error on click.

**To Reproduce**
Steps to reproduce the current behavior:

1. Render Select component
`<FwSelect
          label="Test"
          name="test"
          options={[
            { label: "Mr.", value: "Mr." },
            { label: "Mrs.", value: "Mrs." },
            { label: "Ms.", value: "Ms." },
          ]}
        />`
2. Open in a browser
3. See strange styles
4. Click on the component
5. See the console error and the popup is not opened

**Expected behavior**
Render a select component without the border and not centered, open the popup with options on click

**Screenshots**
<img width="537" alt="Screenshot 2023-06-19 at 13 59 05" src="https://github.com/freshworks/crayons/assets/29632020/d551d079-84d0-49f3-bd10-85754d06be94">
<img width="601" alt="Screenshot 2023-06-19 at 14 00 52" src="https://github.com/freshworks/crayons/assets/29632020/ae558247-79ae-4379-9699-ab12cac297aa">

**Comment by kaushal-freshworks** [comment]
Hello, 
I looked at your bug report. I see one issue is in the options object. The main attributes are "value" and "text". I see in your options object it is "label" and "value". I have attached screen shot of a sample <FwSelect> with the correct attributes. Please try it out once and let us know. 

<img width="1477" alt="Screenshot 2023-06-26 at 4 41 07 PM" src="https://github.com/freshworks/crayons/assets/85667235/1943c0ce-b83f-45f4-b385-755f42bd9bfb">


Regarding the second part in your bug of Strange Styles I am not a 100% sure of what you mean by this. By default the <FwSelect> will take 100% width of the container that contains it. However I have set the width for the <FwSelect>  and shown how you can change the width of the <FwSelect> . Please see above screen shot and note the "style" attribute. 

In the Css you also need to set this attribute 

.App {
  font-family: sans-serif;
  text-align: center;
  --fw-popover-max-width: 100px;
}

This ensures that the options dropdown width is also controlled. 

Hope this helps.

**Comment by kaushal-freshworks** [comment]
You can look at this sample code 
https://codesandbox.io/s/boring-bird-5359hk?file=/src/App.js

**Comment by haass-io** [comment]
@kaushal-freshworks Please update your chrome to the latest. 
Select, date components are broken.

![Screenshot 2023-06-27 at 6 50 15 PM](https://github.com/freshworks/crayons/assets/86523212/0245a638-3857-41b6-a86a-23cd5e577b6f)

**Comment by arvindanta** [comment]
@taraschuiko @haass-io , Can you please try the version 4.2.0-beta.19 ?.

In the latest version of chrome, they have introduced a popover attribute. `https://developer.chrome.com/blog/introducing-popover-api/` .

And this was causing the existing popover functionality to break. This issue has been fixed in the version `4.2.0-beta.19`- `@next` dist tag.

**Comment by suhostv** [comment]
@arvindanta thanks for the explanation, new beta version works well on Chrome 👍
Where can we expect stable version with this fix?

**Comment by suhostv** [comment]
By the way, found one small but annoying bug related to Select component.

As you can see on first screenshot, select component goes over the right corner of parent container by 2 pixels, resulting in bad UI experience.
I've tried to discover what is the issue and found that deep into the component shadow DOM there is a popover component with `.input-container` element that makes mistake calculating its own width. These calculations seems to take into consideration padding but not border width, resulting in 2px mismatch (2 screenshot)

Not sure if you were already aware of this issue, but it is pretty annoying not having Select components aligned with other inputs on the page 🙃

<img width="566" alt="image" src="https://github.com/freshworks/crayons/assets/16260497/fa992344-bd7a-410a-8f0e-4de3c70f2c91">
![select-bug](https://github.com/freshworks/crayons/assets/16260497/30eae3db-1abe-4370-9c34-bc5d7bede3aa)

**Comment by arvindanta** [comment]
@suhostv Please try - @freshworks/crayons@4.2.0. The fix for above is also available in this latest version.
